v = float(input("Enter final velocity "))
u = float(input("Enter initial velocity "))
a = float(input("Enter accerlation "))
Displacement = (v**2 - u**2) / (2*a)
print(f"Displacement is ",Displacement)